<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-08 16:52
=======
# Generated by Django 4.0.5 on 2022-06-09 05:37
>>>>>>> fae48685d59c0b3ee25cfe97a250db36f868d01b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
